Todo App
taiwo2/Todo-app pull request #2
Opened 2021-04-11 22:30 UTC by taiwo2

The look of the User Interface and it's able to do the following:

- view all projects
- view all todos in each project (probably just the title and duedate.. perhaps changing color for different priorities)
- expand a single todo to see/edit its details
- delete a todo

2021-04-12 13:13 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 🛑 

Hello, @taiwo2  great project. I love the design and the way you have styled your application. This was great work 👏🏿 . However, there are a few changes that need to be made. Kindly check the following ⬇️ 

- [ ] Kindly add node_modules to the git ignore. You should not commit the node_modules in your repository. This will keep your repository clean and professional. Kindly delete the node_modules and add them to the git ignore ⬇️ 
![lock_files_requirement](https://user-images.githubusercontent.com/32361963/114399357-82baf180-9ba9-11eb-81ad-727c515ae1a7.png)

- [ ] Kindly the call.js file is empty. Empty files should be deleted. This will keep your project clean and professional. 
- [ ] Kindly add a default project. This is a hard requirement for this project. You can do this by initializing an object with default values when your project is first loaded. ⬇️ 

![projects_requirement](https://user-images.githubusercontent.com/32361963/114399766-f65cfe80-9ba9-11eb-9e7b-5934d9045d22.png)

### if you have any question kindly reach me on slack @peterrobert

### HAPPY CODING 💻

2021-04-12 13:13 UTC, peterrobert commented on src/index.js
> +
- [ ] Kindly don't disable all the eslint rules. Eslint will help you follow coding best practices. Kindly uncomment this and fix all the errors.

2021-04-12 13:13 UTC, peterrobert commented on package.json
> +  },
- [ ] Kindly configure your scripts well. This will ensure that your application uses web pack well. The way you have configured the start script and the dev script is wrong. Actually, if you try running the application using these scripts it will throw an error. ⬇️ 
![scripts_requirement](https://user-images.githubusercontent.com/32361963/114393065-4768f480-9ba2-11eb-8ef1-1b5e81658e29.png)

### hint:
you can configure your script like these:

```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2021-04-13 16:22 UTC, oloomoses approved these changes
# Congratulations, Project Approved. :muscle: :tada: :clap: 
** Great job working on the suggested changes from the previous reviews :muscle: 
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

## Optional
#### even though this requirement is marked as optional, it is a must to implement it before merging
- [ ] Kindly move the .vscode and the node_modules into the .gitignore file. Remember that files and folder that are not part of the project should be added to the .gitignore file

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

2021-05-03 13:54 UTC, merged